//answer, prayer pairs
const raw_prayers = [];
const clean_answered_prayers = [];

const REFLECTED_MESSAGE = "Reflection of a Reflection Reflected Endlessly";

const getWaitingReflections = () => {
  const ret = [];
  for (let r of raw_prayers) {
    //im sure its fine
    if (r && r.prayerObject.message === REFLECTED_MESSAGE) {
      ret.push(r.prayerObject["save-data"])
    }
  }
  return ret;
}


const addNewReflection = (garbage, json) => {
  makeNewRawPrayer("Blessed", json)
}

//responses can be html, prayers can not be
//also if the prayer is a reflection, don't show spam
const makeNewAnsweredPrayer = (prayer, response) => {
  if (!prayer || prayer === REFLECTED_MESSAGE) {
    return;
  }
  clean_answered_prayers.push({ prayer: prayer, response: response })
}
const makeNewRawPrayer = (responseText, prayerObject) => {
  raw_prayers.push({ response: responseText, prayerObject: prayerObject })
}

//JSON.parse(raw_prayers[0].prayerObject["save-data"]) for Reflection
//makeNewRawPrayer("Answer to Prayer", { "message": "can i avoid fucking up my save", "save-data": "{\"hallways_entered\":0,\"prayers_sent\":[\"test with dat\",\"test 3 from d\",\"test 5\",\"million test \",\"can i avoid f\"],\"inventory\":[],\"keys\":13,\"meat\":1,\"candy\":1,\"opened_the_door\":true,\"lastSaveTimeCode\":1788634666203,\"lastLoadTimeCode\":1788634654834}", "date": "9\/5\/2026, 2:57:46 PM", "website": "You passed the test, you're not a particularly stupid bot!" });
//makeNewRawPrayer("Intentionally Broken Prayer2", { "message": "million test with data", "save-data": "{&quot;hallways_entered&quot;:0,&quot;prayers_sent&quot;:[&quot;test with dat&quot;,&quot;test 3 from d&quot;,&quot;test 5&quot;,&quot;million test &quot;],&quot;inventory&quot;:[],&quot;keys&quot;:0,&quot;meat&quot;:1,&quot;candy&quot;:1,&quot;opened_the_door&quot;:true,&quot;lastSaveTimeCode&quot;:1788634287055,&quot;lastLoadTimeCode&quot;:1788634272876}", "date": "9\/5\/2026, 2:51:27 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
//makeNewRawPrayer("tbd",{})

makeNewRawPrayer("zzz", { "message": "May the ritual at October's end succeed \r\n-the catcher of zampanio", "save-data": "{\"hallways_entered\":0,\"prayers_sent\":[\"May the ritua\"],\"inventory\":[],\"meat\":1,\"candy\":1,\"opened_the_door\":true,\"lastSaveTimeCode\":1789447415002,\"lastLoadTimeCode\":1789447249632,\"current_room_id\":\"OUTSIDE\",\"state_changes\":{},\"spooky_seen\":[],\"masks\":0}", "date": "9\/14\/2026, 11:43:35 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("zzz", { "message": "okay :) it successfully eats weird characters and doesnt let me evilly inject random html spans in my text, as far as i could see, i think", "save-data": "{\"hallways_entered\":96,\"prayers_sent\":[\"Hello, miss H\",\"check\u200fing w\u3000h\",\"<span style=\\\"\",\"okay :) it su\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":2,\"stranger\":false,\"candy\":2,\"powerWorking\":false,\"opened_the_door\":true,\"current_room_id\":\"OUTSIDE\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlock\"},\"spooky_seen\":[\"face\",\"jrstairs\"],\"lastSaveTimeCode\":1789480574776,\"lastLoadTimeCode\":1789479963556}", "date": "9\/15\/2026, 9:56:14 AM", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("zzz", { "message": "|Hi Harvest!", "save-data": "{\"hallways_entered\":435632872472961,\"prayers_sent\":[\"|Hi Harvest!\"],\"inventory\":[],\"meat\":999,\"candy\":999,\"opened_the_door\":true,\"lastSaveTimeCode\":1789511403671,\"lastLoadTimeCode\":1789510177481,\"current_room_id\":\"OUTSIDE\",\"button_controls\":false,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlock\",\"2_back_left_locked\":\"2_back_left_m\",\"west_sunroom_left1\":\"west_sunroom_\",\"3_deep3\":\"3_deep3_unloc\",\"3_bright_left1\":\"3_bright_left\",\"3_bright_deep1\":\"3_bright_deep\",\"2_back_left_unlocked_no_mask\":\"2_back_left_m\"},\"keys\":456,\"spooky_seen\":[\"jrstairs\",\"bigfurniture\",\"pumpkinroom\",\"masksky\",\"blind\",\"pumpkinroom\",\"bigfurniture\",\"mirrorwave\",\"bride_and_man\",\"upsidedown\",\"bigchair\",\"clowns\",\"masksky\",\"bride\"],\"masks\":113,\"powerWorking\":true}", "date": "2026-09-16, 00:30:03", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("zzz *grumble* zzz", { "message": "Good luck with the midlife crisis sweetie ^w^", "save-data": "{\"hallways_entered\":0,\"prayers_sent\":[\"Good luck wit\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":false,\"opened_the_door\":false,\"current_room_id\":\"OUTSIDE\",\"button_controls\":true,\"state_changes\":{},\"spooky_seen\":[],\"lastSaveTimeCode\":1789519658377}", "date": "16\/09\/2026, 00:47:38", "website": "You passed the test, you're not a particularly stupid bot!" })


//makeNewRawPrayer("Blessed", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":13,\"prayers_sent\":[],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{},\"spooky_seen\":[],\"lastSaveTimeCode\":1789445162501}", "date": "9\/15\/2026, 12:06:02 AM", "website": "You passed the test, you're not a particularly stupid bot!" })
//"garbage" is there as a dummy variable, i'm lazy and the thing i copy from the php has a , and i want this to too without me having to edit
/*addNewReflection("garbage", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":54,\"prayers_sent\":[],\"inventory\":[],\"keys\":31,\"masks\":13,\"meat\":0,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[],\"lastSaveTimeCode\":1789445662324,\"lastLoadTimeCode\":1789445634693}", "date": "9\/15\/2026, 12:14:22 AM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("garbage", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":39,\"prayers_sent\":[],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[],\"lastSaveTimeCode\":1789445412495,\"lastLoadTimeCode\":1789445397836}", "date": "9\/15\/2026, 12:10:12 AM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("garbage", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":223,\"prayers_sent\":[],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\",\"3_bright_left1\":\"3_bright_left1_mask\",\"3_bright_deep1\":\"3_bright_deep1_open\"},\"spooky_seen\":[\"bigfurniture\",\"bigchair\",\"bride_and_mannequin\",\"mirrorwave\"],\"lastSaveTimeCode\":1789446716610,\"lastLoadTimeCode\":1789446610281}", "date": "9\/15\/2026, 12:31:58 AM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("garbage", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":596,\"prayers_sent\":[],\"inventory\":[],\"keys\":0,\"masks\":1,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\",\"2_back_left_mask\":\"2_back_left_unlocked_no_mask\"},\"spooky_seen\":[\"blind\",\"bride\",\"jrsky\",\"bigfurniture\"],\"lastSaveTimeCode\":1789448567542}", "date": "9\/15\/2026, 12:02:49 AM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("garbage", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":57,\"prayers_sent\":[],\"inventory\":[],\"keys\":31,\"masks\":13,\"meat\":0,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[],\"lastSaveTimeCode\":1789448574784,\"lastLoadTimeCode\":1789448569508}", "date": "9\/15\/2026, 12:02:57 AM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("garbage", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":230,\"prayers_sent\":[],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\",\"3_bright_left1\":\"3_bright_left1_mask\",\"3_bright_deep1\":\"3_bright_deep1_open\"},\"spooky_seen\":[\"bigfurniture\",\"bigchair\",\"bride_and_mannequin\",\"mirrorwave\",\"jars\"],\"lastSaveTimeCode\":1789448589988,\"lastLoadTimeCode\":1789448577251}", "date": "9\/15\/2026, 12:03:12 AM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("garbage", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":249,\"prayers_sent\":[],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[\"bigfurniture\",\"bigchair\",\"bride_and_mannequin\",\"mirrorwave\",\"approved\",\"bride_and_mannequin\"],\"lastSaveTimeCode\":1789448631575,\"lastLoadTimeCode\":1789448592756}", "date": "9\/15\/2026, 12:03:52 AM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("garbage", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":42,\"prayers_sent\":[],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[],\"lastSaveTimeCode\":1789448637089,\"lastLoadTimeCode\":1789448632386}", "date": "9\/15\/2026, 12:03:57 AM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("garbage", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":377,\"prayers_sent\":[],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":1,\"stranger\":false,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\"},\"spooky_seen\":[],\"lastSaveTimeCode\":1789492493533,\"lastLoadTimeCode\":1789491101398}", "date": "15. 9. 2026 19:15:02", "website": "You passed the test, you're not a particularly stupid bot!" })



addNewReflection("garbage", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":46,\"prayers_sent\":[],\"inventory\":[],\"keys\":0,\"masks\":1,\"meat\":0,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\",\"2_back_left_mask\":\"2_back_left_unlocked_no_mask\"},\"spooky_seen\":[],\"lastSaveTimeCode\":1789492521811,\"lastLoadTimeCode\":1789492502375}", "date": "15. 9. 2026 19:15:25", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("garbage", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":87,\"prayers_sent\":[],\"inventory\":[],\"keys\":0,\"masks\":1,\"meat\":0,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\",\"2_back_left_mask\":\"2_back_left_unlocked_no_mask\"},\"spooky_seen\":[\"upsidedown\"],\"lastSaveTimeCode\":1789492737769,\"lastLoadTimeCode\":1789492551574}", "date": "15. 9. 2026 19:18:58", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("garbage", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":647,\"prayers_sent\":[],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":1,\"stranger\":false,\"candy\":1,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[\"foghorse\",\"pumpkinroom\"],\"lastSaveTimeCode\":1789506506211}", "date": "9\/15\/2026, 5:08:35 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("garbage", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":443,\"prayers_sent\":[\"Good luck with the midlife crisis sweetie ^w^\"],\"inventory\":[],\"keys\":0,\"masks\":1,\"meat\":1,\"stranger\":false,\"candy\":1,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\",\"2_back_left_mask\":\"2_back_left_unlocked_no_mask\"},\"spooky_seen\":[\"car\",\"car\",\"blind\",\"evil\",\"truth\",\"car\",\"clowns\"],\"lastSaveTimeCode\":1789520788666}", "date": "16\/09\/2026, 01:06:30", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("garbage", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":224,\"prayers_sent\":[],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\",\"3_bright_left1\":\"3_bright_left1_mask\",\"3_bright_deep1\":\"3_bright_deep1_open\"},\"spooky_seen\":[\"bigfurniture\",\"bigchair\",\"bride_and_mannequin\",\"mirrorwave\"],\"lastSaveTimeCode\":1789520792666,\"lastLoadTimeCode\":1789520790500}", "date": "16\/09\/2026, 01:06:34", "website": "You passed the test, you're not a particularly stupid bot!" })
*/
//start of clownsonas
addNewReflection("garbage", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":170,\"prayers_sent\":[\"Please let this alpha test work.\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"east_main_room1_left1\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[\"bride\"],\"lastSaveTimeCode\":1790133063708,\"lastLoadTimeCode\":1790133063706,\"clownsona\":\"[\\\"body\/body10.png\\\",\\\"face\/smileyWithNose.png\\\",\\\"hats\/blank.png\\\",\\\"extra\/harvestBodypillow.png\\\"]\"}", "date": "9\/22\/2026, 11:11:12 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("gar", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":8,\"prayers_sent\":[],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{},\"spooky_seen\":[],\"lastSaveTimeCode\":1790134197916,\"clownsona\":\"[\\\"body\/fancy.png\\\",\\\"face\/I_Iwithmakeup.png\\\",\\\"hats\/lamp.png\\\",\\\"extra\/exclamationMark.png\\\"]\"}", "date": "9\/22\/2026, 11:30:00 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
//addNewReflection("garbage")
















for (let p of raw_prayers) {
  makeNewAnsweredPrayer(p.prayerObject.message, p.response)
}