//sudden realization on 9/28/26, 2+ months after starting work on this game and with only 3 days left till lavinraca
//i realized i made a game thats
//half old school dungeon crawl
//half one of those fucked up zillow tours
//: 8800 Blue Lick Road,
//https://www.tumblr.com/pain-and-lavender-honey/706658881000062976/please-explore-this-place-with-me-the-3d?source=share

//answer, prayer pairs
const raw_prayers = [];
//can't let them clog up prayers by trying to leave them breaks prayers
const room_dibs_raw = [];
//keyed by roomId (different form scene id), value is array of prayers that made it
const finishedRoomPrayers = {};

const clean_answered_prayers = [];

const REFLECTED_MESSAGE = "Reflection of a Reflection Reflected Endlessly";
const ROOM_LITANY = "Dear, Sweet, Precious Harvest, I pray for a room to replace";

const getWaitingReflections = () => {
  const ret = [];
  for (let r of raw_prayers) {
    //im sure its fine
    if (r && r.prayerObject.message === REFLECTED_MESSAGE) {
      ret.push(r.prayerObject["save-data"])
    }
  }
  return ret;
}

const getDibsForRoom = (id) => {
  const ret = [];
  for (let r of room_dibs_raw) {
    //im sure its fine
    if (r && r.message.includes(ROOM_LITANY)) {
      try {
        const data = JSON.parse(r["save-data"]);
        if (data.current_room_id === id) {
          ret.push({ message: r.message, data })
        }
      } catch (e) {
        console.error(e);
      }
    }
  }
  return ret;
}


const getPendingPrayersForRoom = (id) => {
  const ret = [];
  const mail = fetchPendingCommands();
  for (let r of mail) {
    //im sure its fine
    if (r && r.message.includes(ROOM_LITANY)) {
      try {
        const data = JSON.parse(r["save-data"]);
        if (data.current_room_id === id) {
          ret.push({ message: r.message, data })
        }
      } catch (e) {
        console.error(e);
      }
    }
  }
  return ret;
}


const addNewReflection = (garbage, json) => {
  makeNewRawPrayer("Blessed", json)
}

//responses can be html, prayers can not be
//also if the prayer is a reflection, don't show spam
const autoMakeNewAnsweredPrayer = (prayer, response) => {
  if (!prayer || prayer === REFLECTED_MESSAGE) {
    return;
  }
  clean_answered_prayers.push({ prayer: prayer, response: response })
}
const makeNewRawPrayer = (responseText, prayerObject) => {
  raw_prayers.push({ response: responseText, prayerObject: prayerObject })
}

const addNewRoomDibs = (garbage, json) => {
  room_dibs_raw.push(json)
}

const addNewFinishedRoomPrayer = (id, prayers) => {
  finishedRoomPrayers[id] = prayers;
}

//JSON.parse(raw_prayers[0].prayerObject["save-data"]) for Reflection
//makeNewRawPrayer("Answer to Prayer", { "message": "can i avoid fucking up my save", "save-data": "{\"hallways_entered\":0,\"prayers_sent\":[\"test with dat\",\"test 3 from d\",\"test 5\",\"million test \",\"can i avoid f\"],\"inventory\":[],\"keys\":13,\"meat\":1,\"candy\":1,\"opened_the_door\":true,\"lastSaveTimeCode\":1788634666203,\"lastLoadTimeCode\":1788634654834}", "date": "9\/5\/2026, 2:57:46 PM", "website": "You passed the test, you're not a particularly stupid bot!" });
//makeNewRawPrayer("Intentionally Broken Prayer2", { "message": "million test with data", "save-data": "{&quot;hallways_entered&quot;:0,&quot;prayers_sent&quot;:[&quot;test with dat&quot;,&quot;test 3 from d&quot;,&quot;test 5&quot;,&quot;million test &quot;],&quot;inventory&quot;:[],&quot;keys&quot;:0,&quot;meat&quot;:1,&quot;candy&quot;:1,&quot;opened_the_door&quot;:true,&quot;lastSaveTimeCode&quot;:1788634287055,&quot;lastLoadTimeCode&quot;:1788634272876}", "date": "9\/5\/2026, 2:51:27 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
//makeNewRawPrayer("tbd",{})

makeNewRawPrayer("zzz", { "message": "May the ritual at October's end succeed \r\n-the catcher of zampanio", "save-data": "{\"hallways_entered\":0,\"prayers_sent\":[\"May the ritua\"],\"inventory\":[],\"meat\":1,\"candy\":1,\"opened_the_door\":true,\"lastSaveTimeCode\":1789447415002,\"lastLoadTimeCode\":1789447249632,\"current_room_id\":\"OUTSIDE\",\"state_changes\":{},\"spooky_seen\":[],\"masks\":0}", "date": "9\/14\/2026, 11:43:35 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("zzz", { "message": "okay :) it successfully eats weird characters and doesnt let me evilly inject random html spans in my text, as far as i could see, i think", "save-data": "{\"hallways_entered\":96,\"prayers_sent\":[\"Hello, miss H\",\"check\u200fing w\u3000h\",\"<span style=\\\"\",\"okay :) it su\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":2,\"stranger\":false,\"candy\":2,\"powerWorking\":false,\"opened_the_door\":true,\"current_room_id\":\"OUTSIDE\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlock\"},\"spooky_seen\":[\"face\",\"jrstairs\"],\"lastSaveTimeCode\":1789480574776,\"lastLoadTimeCode\":1789479963556}", "date": "9\/15\/2026, 9:56:14 AM", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("zzz", { "message": "|Hi Harvest!", "save-data": "{\"hallways_entered\":435632872472961,\"prayers_sent\":[\"|Hi Harvest!\"],\"inventory\":[],\"meat\":999,\"candy\":999,\"opened_the_door\":true,\"lastSaveTimeCode\":1789511403671,\"lastLoadTimeCode\":1789510177481,\"current_room_id\":\"OUTSIDE\",\"button_controls\":false,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlock\",\"2_back_left_locked\":\"2_back_left_m\",\"west_sunroom_left1\":\"west_sunroom_\",\"3_deep3\":\"3_deep3_unloc\",\"3_bright_left1\":\"3_bright_left\",\"3_bright_deep1\":\"3_bright_deep\",\"2_back_left_unlocked_no_mask\":\"2_back_left_m\"},\"keys\":456,\"spooky_seen\":[\"jrstairs\",\"bigfurniture\",\"pumpkinroom\",\"masksky\",\"blind\",\"pumpkinroom\",\"bigfurniture\",\"mirrorwave\",\"bride_and_man\",\"upsidedown\",\"bigchair\",\"clowns\",\"masksky\",\"bride\"],\"masks\":113,\"powerWorking\":true}", "date": "2026-09-16, 00:30:03", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("zzz *grumble* zzz", { "message": "Good luck with the midlife crisis sweetie ^w^", "save-data": "{\"hallways_entered\":0,\"prayers_sent\":[\"Good luck wit\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":false,\"opened_the_door\":false,\"current_room_id\":\"OUTSIDE\",\"button_controls\":true,\"state_changes\":{},\"spooky_seen\":[],\"lastSaveTimeCode\":1789519658377}", "date": "16\/09\/2026, 00:47:38", "website": "You passed the test, you're not a particularly stupid bot!" })

makeNewRawPrayer("I will, dear Butler. Thank you for your dilligence wandering my halls.", { "message": "Dearest Harvest, may you yet again prosper this season.", "save-data": "{\"hallways_entered\":647,\"prayers_sent\":[\"Please let th\",\"snor mimimi\",\"Dearest Harve\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"OUTSIDE\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlock\",\"2_back_left_locked\":\"2_back_left_m\",\"2_back_left_unlocked_no_mask\":\"2_back_left_m\"},\"spooky_seen\":[\"bride\",\"masksky\",\"pumpkins\",\"itwrithes\",\"approved\",\"bride\",\"itwrithes\",\"shake\",\"foghorse\",\"jrstairs\",\"tridoor\",\"bride_and_man\"],\"lastSaveTimeCode\":1790810257947,\"lastLoadTimeCode\":1790810193993,\"clownsona\":[\"body/bodyInvi\",\"face/orange.p\",\"hats/KNIFE.pn\",\"extra/spadesT\"],\"books\":0,\"harvestPoints\":0}", "date": "9/30/2026, 7:17:37 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("You are doing wonderfully, Guest. <Br><Br>I provide my Blessing for your Trick or Treating. May Candy fill your bags.", { "message": "I don't know how to pray or if i'm doing this right buuuuut...... i pray that i can hopefully trick or treat with my friends ! and if i can, i hope for lots of candy! may everything in the world rock. lavinrockin' in the manor tonighttttt - masticatedSurrealist ", "save-data": "{\"hallways_entered\":0,\"prayers_sent\":[\"I don't know \"],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":0,\"harvestPoints\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":false,\"opened_the_door\":false,\"current_room_id\":\"OUTSIDE\",\"button_controls\":true,\"state_changes\":{},\"spooky_seen\":[],\"lastSaveTimeCode\":1790810316195,\"clownsona\":[\"body/Body0.pn\",\"face/flesh.pn\",\"hats/dualMask\",\"extra/pumpkin\"]}", "date": "9/30/2026, 7:18:36 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("The Faithful do provide. Thank you for your well wishes. And thank you, truly, for your prayers for the Manor.", { "message": "Welcome back to life! I hope you have a wonderful month. Your house is very cool and beautiful and spooky. ", "save-data": "{\"hallways_entered\":234,\"prayers_sent\":[\"Please let th\",\"Welcome back \"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":1,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"OUTSIDE\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlock\",\"2_back_left_locked\":\"2_back_left_m\",\"2_back_left_unlocked_no_mask\":\"2_back_left_m\"},\"spooky_seen\":[\"bride\"],\"lastSaveTimeCode\":1790810432192,\"lastLoadTimeCode\":1790809806491,\"clownsona\":[\"body/Body1.pn\",\"face/spiralFa\",\"hats/stabbedI\",\"extra/holding\"],\"books\":0,\"harvestPoints\":10}", "date": "01/10/2026, 01:20:32", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("Candy Corn makes a wonderful seasonal decoration, and thankfully it doesn't actually grow in Fields.", { "message": "Oh dear Harvest, I pray for plentiful produce from mine candycorn husks upon this scared and spookiest Harveste Eve. I wish to deck thee halls of Lavinraca with the orange and creme hued candied delights.", "save-data": "{\"hallways_entered\":0,\"prayers_sent\":[\"Oh dear Harve\"],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":0,\"harvestPoints\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":false,\"opened_the_door\":false,\"current_room_id\":\"OUTSIDE\",\"button_controls\":true,\"state_changes\":{},\"spooky_seen\":[],\"lastSaveTimeCode\":1790810453896,\"clownsona\":[\"body/body21.p\",\"face/simpleFa\",\"hats/catEars.\",\"extra/candyBa\"]}", "date": "9/30/2026, 7:20:53 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("May it indeed.", { "message": "May the catcher be catched this october. For the laughs.", "save-data": "{\"hallways_entered\":0,\"prayers_sent\":[\"May the catch\"],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":0,\"harvestPoints\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":false,\"opened_the_door\":false,\"current_room_id\":\"OUTSIDE\",\"button_controls\":false,\"state_changes\":{},\"spooky_seen\":[],\"lastSaveTimeCode\":1790811130875,\"clownsona\":[\"body/stiltWal\",\"face/spiralFa\",\"hats/lamp.png\",\"extra/cupcake\"]}", "date": "9/30/2026, 4:32:10 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("This day is indeed joyous, Faithful. An auspicious start to our season.", { "message": "O' dear harvest. I, Hun, wish you a good day or night whenever you have this prayer reach you", "save-data": "{\"hallways_entered\":748,\"prayers_sent\":[\"Please let th\",\"O' dear harve\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"OUTSIDE\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlock\",\"2_back_left_locked\":\"2_back_left_u\",\"west_sunroom_left1\":\"west_sunroom_\",\"3_deep3\":\"3_deep3_unloc\",\"2_back_left_mask\":\"2_back_left_u\",\"SecretPassagewayWest_deep2\":\"SecretPassage\",\"3_bright_left1\":\"3_bright_left\",\"3_bright_deep1\":\"3_bright_deep\"},\"spooky_seen\":[\"bride\",\"hoon\",\"maccus_ball\",\"tridoor\"],\"lastSaveTimeCode\":1790874927734,\"lastLoadTimeCode\":1790874795018,\"clownsona\":[\"body/FinalAct\",\"face/face9.pn\",\"hats/harlequi\",\"extra/dragonW\"],\"books\":0,\"harvestPoints\":1}", "date": "10/1/2026, 1:15:27 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("I have all the peace I could desire, but Faithful, what I lack are new books to read. Have you any recommendations?", { "message": "May you have the peace to read all you desire.", "save-data": "{\"hallways_entered\":0,\"prayers_sent\":[\"May you have \"],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":0,\"harvestPoints\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":false,\"opened_the_door\":false,\"current_room_id\":\"OUTSIDE\",\"button_controls\":true,\"state_changes\":{},\"spooky_seen\":[],\"lastSaveTimeCode\":1790875881070,\"clownsona\":[\"body/ghostfro\",\"face/face26.p\",\"hats/leaf.png\",\"extra/shoes.p\"]}", "date": "10/1/2026, 1:31:21 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("I'm sorry, I'm sure I would have known if I were the god of money. Sadly, all I can offer you are books I have already read.", { "message": "Dear Harvest, give me money", "save-data": "{\"hallways_entered\":79,\"prayers_sent\":[\"Dear Harvest,\"],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":0,\"harvestPoints\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":false,\"opened_the_door\":true,\"current_room_id\":\"OUTSIDE\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlock\"},\"spooky_seen\":[],\"lastSaveTimeCode\":1790875914664,\"clownsona\":[\"body/fancy.pn\",\"face/face9.pn\",\"hats/KNIFE.pn\",\"extra/exclama\"]}", "date": "01/10/2026, 14:31:54", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("May you have the Inspiration required to make the Change you seek, Faithful, that you may feast on the fruit of your Harvest.", { "message": "Hey can you help me get a job? Like, a good one, no monkey's paw shit. Thanks", "save-data": "{\"hallways_entered\":0,\"prayers_sent\":[\"Hey can you h\"],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":0,\"harvestPoints\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":false,\"opened_the_door\":false,\"current_room_id\":\"OUTSIDE\",\"button_controls\":true,\"state_changes\":{},\"spooky_seen\":[],\"lastSaveTimeCode\":1790877815363,\"clownsona\":[\"body/clownyGh\",\"face/doubleSm\",\"hats/partyHat\",\"extra/rainbow\"]}", "date": "10/1/2026, 1:03:35 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("Unfortunately I am not corporeal in your plane of existence, Faithful.  Perhaps my <a target='_blank' href='http://lavinraca.eyedolgames.com/TheHarvestGames/secrets/In_Her_Library_At_Lavinraca_The_Harvest_Waits_Dreaming-1.pdf'>autobiography</a> will have to suffice.", { "message": "OH MY GOD HI HARVEST I'M A BIG FAN CAN I GET AN AUTOGRAPH", "save-data": "{\"hallways_entered\":0,\"prayers_sent\":[\"OH MY GOD HI \"],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":0,\"harvestPoints\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":false,\"opened_the_door\":false,\"current_room_id\":\"OUTSIDE\",\"button_controls\":true,\"state_changes\":{},\"spooky_seen\":[],\"lastSaveTimeCode\":1790878521250,\"clownsona\":[\"body/FinalAct\",\"face/flesh.pn\",\"hats/leaf.png\",\"extra/scarecr\"]}", "date": "10/1/2026, 1:15:21 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer(".... I .... don't want to think about sleep right now, Guest.<Br><Br> Thank you for your well wishes, all the same.", { "message": "may you sleep well", "save-data": "{\"hallways_entered\":0,\"prayers_sent\":[\"may you sleep\"],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":0,\"harvestPoints\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":false,\"opened_the_door\":false,\"current_room_id\":\"OUTSIDE\",\"button_controls\":true,\"state_changes\":{},\"spooky_seen\":[],\"lastSaveTimeCode\":1790885157074,\"clownsona\":[\"body/body6.pn\",\"face/faceDrip\",\"hats/mushroom\",\"extra/pileOfL\"]}", "date": "10/1/2026, 3:05:57 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("I bless their Inspiration to drive their Hunger.", { "message": "Oh Dear, Sweet, Precious Harvest, I do pray for a Lavinraca rich in sweets and Halloween treats. Also please help my counterparts, myself and myself, tear themselves free of their endless loops of deprivation. Let us be at peace, and let us be joyful, and let us join in the harvest - myself and myself and I.", "save-data": "{\"hallways_entered\":339,\"prayers_sent\":[\"Please let th\",\"Oh Dear, Swee\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":2,\"stranger\":true,\"candy\":3,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"OUTSIDE\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlock\",\"2_back_left_locked\":\"2_back_left_m\",\"2_back_left_unlocked_no_mask\":\"2_back_left_m\",\"1_bright\":\"1_bright_no_b\"},\"spooky_seen\":[\"bride\",\"jrsky\",\"plants\"],\"lastSaveTimeCode\":1790886825963,\"lastLoadTimeCode\":1790886354877,\"clownsona\":[\"body/body15.p\",\"face/smileyMa\",\"hats/halo.png\",\"extra/exclama\"],\"books\":4,\"harvestPoints\":10}", "date": "10/1/2026, 3:33:45 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("Thank you, I am proud to be a ho-meow-ner. Uh. Homeowner. I bless the Inspiration of the season to you.", { "message": "dea harvest ! please let this be a fun season this year . congrats on the homeownership c:", "save-data": "{\"hallways_entered\":1629,\"prayers_sent\":[\"Oh dear Harve\",\"Dear Harvest \",\"dea harvest !\"],\"inventory\":[],\"books\":1,\"keys\":4,\"masks\":0,\"harvestPoints\":10,\"meat\":1,\"stranger\":true,\"candy\":1,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"OUTSIDE\",\"button_controls\":false,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlock\",\"west_sunroom_left1\":\"west_sunroom_\",\"3_deep3\":\"3_deep3_unloc\",\"2_back_left_locked\":\"2_back_left_u\",\"5_bright\":\"5_bright_book\",\"1_bright\":\"1_bright_no_b\",\"2_back_left_mask\":\"2_back_left_u\",\"SecretPassagewayWest_deep2\":\"SecretPassage\",\"3_bright_left1\":\"3_bright_left\",\"3_bright_deep1\":\"3_bright_deep\"},\"spooky_seen\":[\"bigclose\",\"tridoor\",\"bigroommanneq\",\"tridoor\",\"bodies\",\"laugh\",\"hand\",\"somanypumpkin\",\"bride_and_man\",\"mirrorwave\",\"maccus_rotati\",\"masksky\",\"itwrithes\",\"jrsky\",\"tentacles\",\"jrsky\"],\"lastSaveTimeCode\":1790897513006,\"clownsona\":[\"body/body21.p\",\"face/simpleFa\",\"hats/catEars.\",\"extra/candyBa\"],\"lastLoadTimeCode\":1790897254422}", "date": "10/1/2026, 6:31:53 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
makeNewRawPrayer("I bless your Inspiration to drive your Change.", { "message": "I pray for good fortune and success in my ventures.", "save-data": "{\"hallways_entered\":151,\"prayers_sent\":[\"I pray for go\"],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":0,\"harvestPoints\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":false,\"opened_the_door\":true,\"current_room_id\":\"OUTSIDE\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlock\",\"west_sunroom_left1\":\"west_sunroom_\",\"3_deep3\":\"3_deep3_unloc\"},\"spooky_seen\":[],\"lastSaveTimeCode\":1790901099857,\"clownsona\":[\"body/body5.pn\",\"face/mazeAnti\",\"hats/dualMask\",\"extra/shoes2.\"]}", "date": "02/10/2026, 07:31:39", "website": "You passed the test, you're not a particularly stupid bot!" })




//"garbage" is there as a dummy variable, i'm lazy and the thing i copy from the php has a , and i want this to too without me having to edit

//start of clownsonas
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":188,\"prayers_sent\":[\"Please let this alpha test work.\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"east_main_room1_left1\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[\"bride\"],\"lastSaveTimeCode\":1790220689885,\"lastLoadTimeCode\":1790220687576,\"clownsona\":[\"body\/body10.png\",\"face\/smileyWithNose.png\",\"hats\/blank.png\",\"extra\/harvestBodypillow.png\"],\"books\":0}", "date": "9\/23\/2026, 11:31:33 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":172,\"prayers_sent\":[\"Please let this alpha test work.\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"east_main_room1_left1\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[\"bride\"],\"lastSaveTimeCode\":1790220774315,\"lastLoadTimeCode\":1790220774312,\"clownsona\":[\"body\/body8.png\",\"face\/smileyWithNose.png\",\"hats\/coffeeMug.png\",\"extra\/flipOff.png\"],\"books\":0}", "date": "9\/23\/2026, 11:32:57 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":174,\"prayers_sent\":[\"Please let this alpha test work.\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"east_main_room1_left1\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[\"bride\"],\"lastSaveTimeCode\":1790220868515,\"lastLoadTimeCode\":1790220862404,\"clownsona\":[\"body\/checkered.png\",\"face\/face5.png\",\"hats\/halo.png\",\"extra\/HonkHonkNose.png\"],\"books\":0}", "date": "9\/23\/2026, 11:34:29 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":424,\"prayers_sent\":[\"Oh dear Harvest, I pray for plentiful produce from mine candycorn husks upon this scared and spookiest Harveste E\"],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":0,\"harvestPoints\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[],\"lastSaveTimeCode\":1790811483514,\"clownsona\":[\"body/body21.png\",\"face/simpleFace.png\",\"hats/catEars.png\",\"extra/candyBasket.png\"]}", "date": "9/30/2026, 7:38:16 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":14,\"prayers_sent\":[],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":0,\"harvestPoints\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{},\"spooky_seen\":[],\"lastSaveTimeCode\":1790809783155,\"clownsona\":[\"body/body21.png\",\"face/faceDripping.png\",\"hats/partyHat.png\",\"extra/biblicallyAccurateAngel.png\"]}", "date": "01/10/2026, 01:09:44", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":581,\"prayers_sent\":[\"Please let this alpha test work.\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\"},\"spooky_seen\":[\"bride\"],\"lastSaveTimeCode\":1790813025329,\"lastLoadTimeCode\":1790812392442,\"clownsona\":[\"body/body7.png\",\"face/face20.png\",\"hats/NonFishRuffle.png\",\"extra/floatingEyes.png\"],\"books\":0,\"harvestPoints\":0}", "date": "9/30/2026, 8:03:48 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":425,\"prayers_sent\":[\"Oh dear Harvest, I pray for plentiful produce from mine candycorn husks upon this scared and spookiest Harveste E\"],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":0,\"harvestPoints\":0,\"meat\":0,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[],\"lastSaveTimeCode\":1790899765827,\"clownsona\":[\"body/body21.png\",\"face/simpleFace.png\",\"hats/catEars.png\",\"extra/candyBasket.png\"],\"lastLoadTimeCode\":1790899763826}", "date": "10/1/2026, 7:09:28 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":827,\"prayers_sent\":[],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":1,\"harvestPoints\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\",\"2_back_left_mask\":\"2_back_left_unlocked_no_mask\"},\"spooky_seen\":[\"pumpkins\"],\"lastSaveTimeCode\":1790899852170,\"clownsona\":[\"body/body8.png\",\"face/smileyWithNose.png\",\"hats/coffeeMug.png\",\"extra/flipOff.png\"]}", "date": "10/1/2026, 7:10:54 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":827,\"prayers_sent\":[],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":1,\"harvestPoints\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\",\"2_back_left_mask\":\"2_back_left_unlocked_no_mask\"},\"spooky_seen\":[\"pumpkins\"],\"lastSaveTimeCode\":1790899852170,\"clownsona\":[\"body/body8.png\",\"face/smileyWithNose.png\",\"hats/coffeeMug.png\",\"extra/flipOff.png\"]}", "date": "10/1/2026, 7:10:54 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":929,\"prayers_sent\":[\"Please let this alpha test work.\"],\"inventory\":[],\"keys\":0,\"masks\":1,\"meat\":1,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"1_bright\":\"1_bright_no_book\",\"2_back_left_mask\":\"2_back_left_unlocked_no_mask\"},\"spooky_seen\":[\"bride\",\"bigroommannequin\",\"lady\",\"knives\",\"tridoor\",\"theblackhall\",\"tridoor\",\"mob_for_maccus\"],\"lastSaveTimeCode\":1790899493828,\"lastLoadTimeCode\":1790898538433,\"clownsona\":[\"body/checkered.png\",\"face/face5.png\",\"hats/halo.png\",\"extra/HonkHonkNose.png\"],\"books\":1,\"harvestPoints\":1}", "date": "10/1/2026, 8:04:55 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":1713,\"prayers_sent\":[\"Oh dear Harvest, I pray for plentiful produce from mine candycorn husks upon this scared and spookiest Harveste E\",\"Dear Harvest , please   let this be a fun season for my  first year c:\",\"dea harvest ! please let this be a fun season this year . congrats on the homeownership c:\"],\"inventory\":[],\"books\":1,\"keys\":4,\"masks\":0,\"harvestPoints\":10,\"meat\":1,\"stranger\":true,\"candy\":1,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":false,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\",\"5_bright\":\"5_bright_book_got\",\"1_bright\":\"1_bright_no_book\",\"2_back_left_mask\":\"2_back_left_unlocked_no_mask\",\"SecretPassagewayWest_deep2\":\"SecretPassagewayWest_deep2_open\",\"3_bright_left1\":\"3_bright_left1_mask\",\"3_bright_deep1\":\"3_bright_deep1_open\"},\"spooky_seen\":[\"bigclose\",\"tridoor\",\"bigroommannequin\",\"tridoor\",\"bodies\",\"laugh\",\"hand\",\"somanypumpkins\",\"bride_and_mannequin\",\"mirrorwave\",\"maccus_rotation\",\"masksky\",\"itwrithes\",\"jrsky\",\"tentacles\",\"jrsky\"],\"lastSaveTimeCode\":1790897700462,\"clownsona\":[\"body/body21.png\",\"face/simpleFace.png\",\"hats/catEars.png\",\"extra/candyBasket.png\"],\"lastLoadTimeCode\":1790897254422}", "date": "10/1/2026, 6:35:03 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":1704,\"prayers_sent\":[\"Please let this alpha test work.\"],\"inventory\":[],\"keys\":143,\"masks\":51,\"meat\":0,\"stranger\":true,\"candy\":6,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\",\"1_bright\":\"1_bright_no_book\",\"SecretPassagewayWest_deep2\":\"SecretPassagewayWest_deep2_open\",\"3_bright_left1\":\"3_bright_left1_mask\",\"3_bright_deep1\":\"3_bright_deep1_open\",\"5_bright\":\"5_bright_book_got\",\"SecretPassageway_right2\":\"SecretPassageway_right2_safe_plundered\",\"SecretPassagewayWest_left1\":\"SecretPassagewayWest_left1_plundered\",\"east_first_1_locked\":\"east_first_1_enter\"},\"spooky_seen\":[\"bride\",\"maccus_sprint\",\"lady\",\"bigclose\",\"evil\",\"jrsky\",\"masksky\",\"bride\",\"jrstairs\",\"bride_with_friends\",\"maccus_rotation\",\"stick\",\"jrstairs\",\"approved\",\"hoon\",\"bodies\",\"masksky\",\"tridoor\",\"approved\",\"tridoor\",\"plantsandblocks\",\"bodies\",\"somanypumpkins\",\"tridoor\",\"bride\",\"fuckeduphorse\",\"blind\",\"masksky\",\"itwrithes\",\"maccus_ball\",\"jrsky\",\"evil\",\"jrstairs\",\"plants\",\"approved\",\"maccus_ball\",\"bigfurniture\",\"somanypumpkins\",\"approved\",\"mirrorwave\",\"blind\",\"bride\",\"hand\",\"blind\",\"plantsandblocks\",\"jars\",\"pumpkinroom\",\"somanypumpkins\",\"theblackhall\",\"jrstairs\",\"itwrithes\",\"maccus_ball\",\"bigclose\"],\"lastSaveTimeCode\":1790894346087,\"lastLoadTimeCode\":1790890806716,\"clownsona\":[\"body/body10.png\",\"face/smileyWithNose.png\",\"hats/blank.png\",\"extra/harvestBodypillow.png\"],\"books\":376,\"harvestPoints\":34}", "date": "10/1/2026, 10:39:07 PM", "website": "You passed the test, you're not a particularly stupid bot!" })

//this one is PROBABLY glitched to hell and back but who am i to stop them
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":435632872475706,\"prayers_sent\":[],\"inventory\":[],\"meat\":1001,\"candy\":1001,\"opened_the_door\":true,\"lastSaveTimeCode\":1790891714040,\"lastLoadTimeCode\":1790891485507,\"current_room_id\":\"Stairs_deep2\",\"button_controls\":false,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_mask\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"3_bright_left1\":\"3_bright_left1_mask\",\"3_bright_deep1\":\"3_bright_deep1_open\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\",\"SecretPassagewayWest_deep2\":\"SecretPassagewayWest_deep2_open\",\"SecretPassageway_right2\":\"SecretPassageway_right2_safe_plundered\",\"SecretPassagewayWest_left1\":\"SecretPassagewayWest_left1_plundered\",\"1_bright\":\"1_bright_no_book\",\"5_bright\":\"5_bright_book_got\",\"east_first_1_locked\":\"east_first_1_enter\"},\"keys\":456,\"spooky_seen\":[\"jrstairs\",\"bigfurniture\",\"pumpkinroom\",\"masksky\",\"blind\",\"pumpkinroom\",\"bigfurniture\",\"mirrorwave\",\"bride_and_mannequin\",\"upsidedown\",\"bigchair\",\"clowns\",\"masksky\",\"bride\",\"evil\",\"masksky\",\"stick\",\"bigclose\",\"bigclose\",\"somanypumpkins\",\"blind\",\"river\",\"bigroommannequin\",\"jrstairs\",\"masksky\",\"deepstairs\",\"bigfurniture\",\"shake\",\"bigchair\",\"hand\",\"jrstairs\",\"masksky\",\"where\",\"river\",\"hand\",\"clowns\",\"blind\",\"masksky\",\"laugh\",\"masksky\",\"tentacles\",\"upsidedown\",\"tentacles\",\"somanypumpkins\",\"somanypumpkins\",\"car\",\"deepstairs\",\"hoon\",\"corridor\",\"lady\",\"shake\",\"car\",\"river\",\"face\",\"subtle\",\"bigroommannequin\",\"tridoor\",\"voiddoor\",\"subtle\",\"tridoor\",\"voiddoor\",\"foghorse\",\"approved\",\"maccus_sprint\",\"jars\",\"shake\",\"hoon\",\"bodies\",\"pumpkins\",\"tridoor\",\"bigroommannequin\",\"car\",\"bigchair\",\"jrstairs\",\"approved\",\"bride_and_mannequin\",\"foghorse\",\"stick\",\"jars\",\"hoon\",\"pumpkinroom\",\"bigclose\",\"bigclose\",\"river\",\"subtle\",\"tridoor\",\"pumpkinroom\",\"evil\",\"bigclose\",\"tridoor\",\"masksky\",\"masks\",\"bigclose\",\"lady\",\"pumpkins\",\"maccus_ball\",\"tridoor\",\"blind\",\"bigclose\",\"corridor\",\"corridor\",\"tridoor\",\"bigroommannequin\",\"foghorse\",\"tridoor\"],\"masks\":113,\"powerWorking\":true,\"clownsona\":[\"body/body16.png\",\"face/I_I.png\",\"hats/KNIFE.png\",\"extra/tooMuchCorn.png\"],\"books\":65637,\"harvestPoints\":9999}", "date": "2026-10-01, 23:56:51", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":2081,\"prayers_sent\":[],\"inventory\":[],\"books\":6,\"keys\":0,\"masks\":0,\"harvestPoints\":1,\"meat\":2,\"stranger\":true,\"candy\":2,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"1_bright\":\"1_bright_no_book\",\"5_bright\":\"5_bright_book_got\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\",\"SecretPassageway_right2\":\"SecretPassageway_right2_safe_plundered\",\"SecretPassagewayWest_left1\":\"SecretPassagewayWest_left1_plundered\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\"},\"spooky_seen\":[\"stick\",\"tridoor\",\"river\",\"laugh\",\"bride_and_mannequin\",\"corridor\",\"bride_and_mannequin\",\"voiddoor\",\"knives\",\"knives\",\"car\",\"car\",\"evil\",\"bigclose\",\"bodies\",\"mob_for_maccus\",\"car\",\"hand\",\"river\",\"knives\",\"clowns\",\"blind\",\"shake\",\"evil\",\"stick\",\"tridoor\",\"somanypumpkins\",\"car\",\"face\",\"tridoor\"],\"lastSaveTimeCode\":1790890804183,\"clownsona\":[\"body/body21.png\",\"face/faceDripping.png\",\"hats/partyHat.png\",\"extra/biblicallyAccurateAngel.png\"],\"lastLoadTimeCode\":1790890093335}", "date": "10/1/2026, 9:40:06 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":15,\"prayers_sent\":[],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":0,\"harvestPoints\":0,\"meat\":0,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{},\"spooky_seen\":[],\"lastSaveTimeCode\":1790886783685,\"clownsona\":[\"body/body21.png\",\"face/faceDripping.png\",\"hats/partyHat.png\",\"extra/biblicallyAccurateAngel.png\"],\"lastLoadTimeCode\":1790886781683}", "date": "10/1/2026, 4:33:07 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":494,\"prayers_sent\":[\"Please let this alpha test work.\",\"wake up soon so we can have fun together\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":1,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"east_main_room1_left1\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\",\"2_back_left_mask\":\"2_back_left_unlocked_no_mask\",\"SecretPassagewayWest_deep2\":\"SecretPassagewayWest_deep2_open\",\"3_bright_left1\":\"3_bright_left1_mask\",\"3_bright_deep1\":\"3_bright_deep1_open\"},\"spooky_seen\":[\"bride\",\"clowns\",\"mob_for_maccus\",\"maccus_ball\",\"masks\",\"jrstairs\",\"plantsandblocks\",\"bride_and_mannequin\",\"face\",\"maccus_rotation\",\"approved\",\"jars\",\"bigfurniture\",\"maccus_ball\",\"pumpkins\",\"river\"],\"lastSaveTimeCode\":1790886777330,\"lastLoadTimeCode\":1790885445271,\"clownsona\":[\"body/body10.png\",\"face/smileyWithNose.png\",\"hats/blank.png\",\"extra/harvestBodypillow.png\"],\"books\":0,\"harvestPoints\":10}", "date": "10/1/2026, 4:33:01 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":545,\"prayers_sent\":[\"may you sleep well\"],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":1,\"harvestPoints\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\"},\"spooky_seen\":[],\"lastSaveTimeCode\":1790885900685,\"clownsona\":[\"body/body6.png\",\"face/faceDripping.png\",\"hats/mushrooms.png\",\"extra/pileOfLeaves.png\"]}", "date": "10/1/2026, 3:18:23 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":432,\"prayers_sent\":[\"Please let this alpha test work.\",\"Your Paradox rakes /\\nLeaves from your altar, so we /\\nMay worship anew. /\\nGuide us, if you please, upon /\\nThis end\"],\"inventory\":[],\"keys\":0,\"masks\":1,\"meat\":0,\"stranger\":true,\"candy\":2,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\",\"1_bright\":\"1_bright_no_book\",\"2_back_left_mask\":\"2_back_left_unlocked_no_mask\"},\"spooky_seen\":[\"bride\",\"jrsky\",\"jrsky\",\"corridor\"],\"lastSaveTimeCode\":1790884682844,\"lastLoadTimeCode\":1790883090560,\"clownsona\":[\"body/SillyCloak.png\",\"face/face18.png\",\"hats/witchHat.png\",\"extra/holdingLantern.png\"],\"books\":1,\"harvestPoints\":10}", "date": "10/1/2026, 3:58:05 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":15,\"prayers_sent\":[],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":0,\"harvestPoints\":0,\"meat\":0,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{},\"spooky_seen\":[],\"lastSaveTimeCode\":1790880054458,\"clownsona\":[\"body/body21.png\",\"face/faceDripping.png\",\"hats/partyHat.png\",\"extra/biblicallyAccurateAngel.png\"],\"lastLoadTimeCode\":1790880052456}", "date": "10/1/2026, 1:40:55 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":370,\"prayers_sent\":[\"Please let this alpha test work.\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":1,\"stranger\":true,\"candy\":1,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\",\"1_bright\":\"1_bright_no_book\"},\"spooky_seen\":[\"bride\",\"jars\",\"maccus_rotation\",\"plants\",\"bodies\",\"maccus_ball\"],\"lastSaveTimeCode\":1790879893250,\"lastLoadTimeCode\":1790879055688,\"clownsona\":[\"body/body14.png\",\"face/EYE.png\",\"hats/halo.png\",\"extra/floatingEyes.png\"],\"books\":1,\"harvestPoints\":10}", "date": "10/1/2026, 1:38:16 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewReflection("", { "message": "Reflection of a Reflection Reflected Endlessly", "save-data": "{\"hallways_entered\":333,\"prayers_sent\":[\"OH MY GOD HI HARVEST I'M A BIG FAN CAN I GET AN AUTOGRAPH\"],\"inventory\":[],\"books\":0,\"keys\":0,\"masks\":0,\"harvestPoints\":0,\"meat\":0,\"stranger\":false,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"2_back_right\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[\"corridor\",\"jrstairs\"],\"lastSaveTimeCode\":1790879048945,\"clownsona\":[\"body/FinalAct.png\",\"face/flesh.png\",\"hats/leaf.png\",\"extra/scarecrowPumpkinHeadOnGround.png\"]}", "date": "10/1/2026, 1:24:15 PM", "website": "You passed the test, you're not a particularly stupid bot!" })


//addNewReflection("garbage")




addNewRoomDibs("garbage", { "message": "Dear, Sweet, Precious Harvest, I pray for a room to replace east_main_room3_deep1 and Sacrificing 1 books in your name. \r\n  I want it to be Waste themed. \r\n  I also want to copy Toilet,Drawers, and Drawers from other rooms of the house and place them inside, if they'll fit.\r\n  Catalyst here. We doing the lobster image right? And sticky notes. Tysm for linking my funeralSim. Also I am 100% fine with roommates. We have two toilets! It'll be just like the year 1 bathroom sleepover!\r\n  I claim this room for myself.\r\n  ", "save-data": "{\"hallways_entered\":212,\"prayers_sent\":[\"Please let this alpha test work.\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":1,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"east_main_room3_deep1\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[\"bride\"],\"lastSaveTimeCode\":1790809960817,\"lastLoadTimeCode\":1790809806491,\"clownsona\":[\"body/Body1.png\",\"face/spiralFancy.png\",\"hats/stabbedInTorso.png\",\"extra/holdingKnife.png\"],\"books\":1,\"harvestPoints\":1}", "date": "01/10/2026, 01:14:36", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewRoomDibs("garbage", { "message": "Dear, Sweet, Precious Harvest, I pray for a room to replace east_first_room1_deep1 and Sacrificing 1 books in your name. \r\n  I want it to be Apocalypse themed. \r\n  I also want to copy Harvest Head,Mirror, and Mirror from other rooms of the house and place them inside, if they'll fit.\r\n  Hi please put this in a painting: https://numberonelabyrinthenjoyer.neocities.org/Resources/Lavinraca/CharmMyth.png\r\n\r\nIt's my little Shrine Corner! ^w^\r\n  I claim this room for myself.\r\n  ", "save-data": "{\"hallways_entered\":820,\"prayers_sent\":[\"Please let this alpha test work.\",\"snor mimimi\",\"Dearest Harvest, may you yet again prosper this season.\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":1,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"east_first_room1_deep1\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\",\"east_first_1_locked\":\"east_first_1_enter\"},\"spooky_seen\":[\"bride\",\"masksky\",\"pumpkins\",\"itwrithes\",\"approved\",\"bride\",\"itwrithes\",\"shake\",\"foghorse\",\"jrstairs\",\"tridoor\",\"bride_and_mannequin\",\"tridoor\",\"masksky\",\"tridoor\",\"bride\",\"bride\",\"family\",\"laugh\",\"tridoor\",\"stick\"],\"lastSaveTimeCode\":1790810592123,\"lastLoadTimeCode\":1790810526559,\"clownsona\":[\"body/bodyInvisible.png\",\"face/orange.png\",\"hats/KNIFE.png\",\"extra/spadesTailfromLavinraca.png\"],\"books\":1,\"harvestPoints\":1}", "date": "9/30/2026, 7:24:20 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewRoomDibs("garbage", { "message": "Dear, Sweet, Precious Harvest, I pray for a room to replace east_main_room3_deep1 and Sacrificing 9999 books in your name. \r\n  I want it to be Waste themed. \r\n  I also want to copy Mirror,Toilet, and Mirror from other rooms of the house and place them inside, if they'll fit.\r\n  Let's try to cram as many roommates into one room as possible. There's no way this could ever go horribly wrong.\r\n\r\n-Personality of Prophetic Secrets/Muse of Mirrors\r\n  I claim this room for myself.\r\n  ", "save-data": "{\"hallways_entered\":435632872475171,\"prayers_sent\":[],\"inventory\":[],\"meat\":1001,\"candy\":1001,\"opened_the_door\":true,\"lastSaveTimeCode\":1790810126277,\"lastLoadTimeCode\":1790809816520,\"current_room_id\":\"east_main_room3_deep1\",\"button_controls\":false,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_mask\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"3_bright_left1\":\"3_bright_left1_mask\",\"3_bright_deep1\":\"3_bright_deep1_open\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\",\"SecretPassagewayWest_deep2\":\"SecretPassagewayWest_deep2_open\",\"SecretPassageway_right2\":\"SecretPassageway_right2_safe_plundered\",\"SecretPassagewayWest_left1\":\"SecretPassagewayWest_left1_plundered\",\"1_bright\":\"1_bright_no_book\",\"5_bright\":\"5_bright_book_got\",\"east_first_1_locked\":\"east_first_1_enter\"},\"keys\":455,\"spooky_seen\":[\"jrstairs\",\"bigfurniture\",\"pumpkinroom\",\"masksky\",\"blind\",\"pumpkinroom\",\"bigfurniture\",\"mirrorwave\",\"bride_and_mannequin\",\"upsidedown\",\"bigchair\",\"clowns\",\"masksky\",\"bride\",\"evil\",\"masksky\",\"stick\",\"bigclose\",\"bigclose\",\"somanypumpkins\",\"blind\",\"river\",\"bigroommannequin\",\"jrstairs\",\"masksky\",\"deepstairs\",\"bigfurniture\",\"shake\",\"bigchair\",\"hand\",\"jrstairs\",\"masksky\",\"where\",\"river\",\"hand\",\"clowns\",\"blind\",\"masksky\",\"laugh\",\"masksky\",\"tentacles\",\"upsidedown\",\"tentacles\",\"somanypumpkins\",\"somanypumpkins\",\"car\",\"deepstairs\",\"hoon\",\"corridor\",\"lady\",\"shake\",\"car\",\"river\",\"face\",\"subtle\",\"bigroommannequin\",\"tridoor\",\"voiddoor\",\"subtle\",\"tridoor\",\"voiddoor\",\"foghorse\",\"approved\",\"maccus_sprint\",\"jars\",\"shake\",\"hoon\",\"bodies\",\"pumpkins\",\"tridoor\",\"bigroommannequin\",\"car\",\"bigchair\",\"jrstairs\",\"approved\",\"bride_and_mannequin\",\"foghorse\",\"stick\",\"jars\",\"hoon\",\"pumpkinroom\",\"bigclose\"],\"masks\":113,\"powerWorking\":true,\"clownsona\":[\"body/body16.png\",\"face/I_I.png\",\"hats/KNIFE.png\",\"extra/tooMuchCorn.png\"],\"books\":75636,\"harvestPoints\":9999}", "date": "2026-10-01, 01:25:27", "website": "You passed the test, you're not a particularly stupid bot!" })
//addNewRoomDibs("", { "message": "Dear, Sweet, Precious Harvest, I pray for a room to replace east_first_room2_deep1 and Sacrificing 1 books in your name. \r\n  I want it to be Identity themed. \r\n  I also want to copy Mirror,Mirror, and Mirror from other rooms of the house and place them inside, if they'll fit.\r\n  imagine if there was a mirror maze here\r\n  I do NOT claim this room for myself.\r\n  ", "save-data": "{\"hallways_entered\":802,\"prayers_sent\":[\"Please let this alpha test work.\",\"O' dear harvest. I, Hun, wish you a good day or night whenever you have this prayer reach you\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":1,\"stranger\":true,\"candy\":1,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"east_first_room2_deep1\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"2_back_left_mask\":\"2_back_left_unlocked_no_mask\",\"SecretPassagewayWest_deep2\":\"SecretPassagewayWest_deep2_open\",\"3_bright_left1\":\"3_bright_left1_mask\",\"3_bright_deep1\":\"3_bright_deep1_open\",\"1_bright\":\"1_bright_no_book\",\"SecretPassageway_right2\":\"SecretPassageway_right2_safe_plundered\",\"SecretPassagewayWest_left1\":\"SecretPassagewayWest_left1_plundered\"},\"spooky_seen\":[\"bride\",\"hoon\",\"maccus_ball\",\"tridoor\",\"voiddoor\"],\"lastSaveTimeCode\":1790875315675,\"lastLoadTimeCode\":1790874795018,\"clownsona\":[\"body/FinalAct.png\",\"face/face9.png\",\"hats/harlequinHorns.png\",\"extra/dragonWing.png\"],\"books\":2,\"harvestPoints\":1}", "date": "10/1/2026, 1:22:51 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
//addNewRoomDibs("", { "message": "Dear, Sweet, Precious Harvest, I pray for a room to replace east_first_room3_deep1 and Sacrificing 13 books in your name. \r\n  I want it to be Spiral themed. \r\n  I also want to copy Mannequin Vat,Bookshelves, and Harvest Head from other rooms of the house and place them inside, if they'll fit.\r\n  when halls become kaldescones. make this one a show not to be missed as time anomallies restr within\r\n  I do NOT claim this room for myself.\r\n  ", "save-data": "{\"hallways_entered\":2170,\"prayers_sent\":[\"Please let this alpha test work.\",\"O' dear harvest. I, Hun, wish you a good day or night whenever you have this prayer reach you\"],\"inventory\":[],\"keys\":4,\"masks\":12,\"meat\":2,\"stranger\":true,\"candy\":2,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"east_first_room3_deep1\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"2_back_left_mask\":\"2_back_left_unlocked_no_mask\",\"SecretPassagewayWest_deep2\":\"SecretPassagewayWest_deep2_open\",\"3_bright_left1\":\"3_bright_left1_mask\",\"3_bright_deep1\":\"3_bright_deep1_open\",\"1_bright\":\"1_bright_no_book\",\"SecretPassageway_right2\":\"SecretPassageway_right2_safe_plundered\",\"SecretPassagewayWest_left1\":\"SecretPassagewayWest_left1_plundered\"},\"spooky_seen\":[\"bride\",\"hoon\",\"maccus_ball\",\"tridoor\",\"voiddoor\",\"hoon\",\"plants\",\"tridoor\",\"somanypumpkins\",\"masksky\",\"voiddoor\",\"bride_with_friends\",\"deepstairs\",\"river\"],\"lastSaveTimeCode\":1790877952935,\"lastLoadTimeCode\":1790874795018,\"clownsona\":[\"body/FinalAct.png\",\"face/face9.png\",\"hats/harlequinHorns.png\",\"extra/dragonWing.png\"],\"books\":293,\"harvestPoints\":13}", "date": "10/1/2026, 2:10:25 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewRoomDibs("", { "message": "Dear, Sweet, Precious Harvest, I pray for a room to replace east_third_room3_deep1 and Sacrificing 1 books in your name. \r\n  I want it to be Technology themed. \r\n  I also want to copy Safe,Mannequin Vat, and Drawers from other rooms of the house and place them inside, if they'll fit.\r\n  the amazing scp site Z13 would like to be included\r\nuhh here are the guys\r\nhttps://ibb.co/N5tNrWC\r\n  I claim this room for myself.\r\n  ", "save-data": "{\"hallways_entered\":272,\"prayers_sent\":[\"Please let this alpha test work.\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":1,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"east_third_room3_deep1\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[\"bride\",\"jars\",\"maccus_rotation\"],\"lastSaveTimeCode\":1790879341684,\"lastLoadTimeCode\":1790879055688,\"clownsona\":[\"body/body14.png\",\"face/EYE.png\",\"hats/halo.png\",\"extra/floatingEyes.png\"],\"books\":1,\"harvestPoints\":1}", "date": "10/1/2026, 1:35:56 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewRoomDibs("", { "message": "Dear, Sweet, Precious Harvest, I pray for a room to replace east_third_room1_deep1 and Sacrificing 1 books in your name. \r\n  I want it to be Censorship themed. \r\n  I also want to copy Masked Figure,Veiled Figure, and Masked Figure from other rooms of the house and place them inside, if they'll fit.\r\n  ████ ████████ ███ ██████████████ █████████\r\n  I do NOT claim this room for myself.\r\n  ", "save-data": "{\"hallways_entered\":277,\"prayers_sent\":[\"Please let this alpha test work.\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":1,\"stranger\":true,\"candy\":1,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"east_third_room1_deep1\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[\"bride\",\"subtle\",\"mob_for_maccus\"],\"lastSaveTimeCode\":1790880218118,\"lastLoadTimeCode\":1790880055240,\"clownsona\":[\"body/cultistfromLavinraca.png\",\"face/mazeNOTantialiased.png\",\"hats/halo.png\",\"extra/0butjustexperimental_its_sojanky_imnotsorry.png\"],\"books\":4,\"harvestPoints\":1}", "date": "10/1/2026, 1:44:53 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewRoomDibs("", { "message": "Dear, Sweet, Precious Harvest, I pray for a room to replace east_third_room2_deep1 and Sacrificing 1 books in your name. \r\n  I want it to be Endings themed. \r\n  I also want to copy Desk,Bookshelves, and Chair from other rooms of the house and place them inside, if they'll fit.\r\n  Hi!!! Honestly I'm fine with anything as long as it's mildly aesthetically pleasing. I like a few of the themes, so much so I'm not sure which one to choose. If you have one besides the one that I selected that you think would fit me more, go ahead and use that! -Yours Untruly, Eon\r\n\r\n  I claim this room for myself.\r\n  ", "save-data": "{\"hallways_entered\":261,\"prayers_sent\":[\"Please let this alpha test work.\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":true,\"candy\":1,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"east_third_room2_deep1\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[\"bride\",\"jrsky\",\"jrsky\"],\"lastSaveTimeCode\":1790883507399,\"lastLoadTimeCode\":1790883090560,\"clownsona\":[\"body/SillyCloak.png\",\"face/face18.png\",\"hats/witchHat.png\",\"extra/holdingLantern.png\"],\"books\":1,\"harvestPoints\":1}", "date": "10/1/2026, 3:43:38 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
addNewRoomDibs("", { "message": "Dear, Sweet, Precious Harvest, I pray for a room to replace east_third_room1_deep1 and Sacrificing 1 books in your name. \r\n  I want it to be Questing themed. \r\n  I also want to copy Mirror,Mirror, and Mirror from other rooms of the house and place them inside, if they'll fit.\r\n  Dear Harvest, prithee grant me this room so that I may bring yet more, yet more, yet more into the fold. No single thing shall be a single thing - behold, mirrors three, arranged so, and Fourfold shall the Harvest be! Only in dreams could a place like this exist... ah, to see yourself from every angle!\r\n  I claim this room for myself.\r\n  ", "save-data": "{\"hallways_entered\":265,\"prayers_sent\":[\"Please let this alpha test work.\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":0,\"stranger\":true,\"candy\":1,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"east_third_room1_deep1\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_mask\",\"2_back_left_unlocked_no_mask\":\"2_back_left_mask\"},\"spooky_seen\":[\"bride\",\"jrsky\",\"plants\"],\"lastSaveTimeCode\":1790886495964,\"lastLoadTimeCode\":1790886354877,\"clownsona\":[\"body/body15.png\",\"face/smileyMask.png\",\"hats/halo.png\",\"extra/exclamationMark.png\"],\"books\":1,\"harvestPoints\":1}", "date": "10/1/2026, 3:30:27 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
//addNewRoomDibs("", { "message": "Dear, Sweet, Precious Harvest, I pray for a room to replace east_first_room3_deep1 and Sacrificing 1 books in your name. \r\n  I want it to be Dolls themed. \r\n  I also want to copy Mirror,Masked Figure, and Veiled Figure from other rooms of the house and place them inside, if they'll fit.\r\n  here's my childhood plush id like to put on the wall. His name is Kangaroo and is 25 years old! https://www.deviantart.com/zepoch/art/Tribute-1387149813\r\n  I claim this room for myself.\r\n  ", "save-data": "{\"hallways_entered\":414,\"prayers_sent\":[\"Please let this alpha test work.\",\"wake up soon so we can have fun together\"],\"inventory\":[],\"keys\":0,\"masks\":0,\"meat\":1,\"stranger\":true,\"candy\":0,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"east_first_room3_deep1\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\",\"2_back_left_mask\":\"2_back_left_unlocked_no_mask\",\"SecretPassagewayWest_deep2\":\"SecretPassagewayWest_deep2_open\",\"3_bright_left1\":\"3_bright_left1_mask\",\"3_bright_deep1\":\"3_bright_deep1_open\"},\"spooky_seen\":[\"bride\",\"clowns\",\"mob_for_maccus\",\"maccus_ball\",\"masks\",\"jrstairs\",\"plantsandblocks\",\"bride_and_mannequin\",\"face\",\"maccus_rotation\",\"approved\",\"jars\",\"bigfurniture\",\"maccus_ball\",\"pumpkins\",\"river\"],\"lastSaveTimeCode\":1790885627131,\"lastLoadTimeCode\":1790885445271,\"clownsona\":[\"body/body10.png\",\"face/smileyWithNose.png\",\"hats/blank.png\",\"extra/harvestBodypillow.png\"],\"books\":1,\"harvestPoints\":1}", "date": "10/1/2026, 4:30:58 PM", "website": "You passed the test, you're not a particularly stupid bot!" })
//addNewRoomDibs("", { "message": "Dear, Sweet, Precious Harvest, I pray for a room to replace east_first_room3_deep1 and Sacrificing 1 books in your name. \r\n  I want it to be Addiction themed. \r\n  I also want to copy Bed,Harvest Head, and Mirror from other rooms of the house and place them inside, if they'll fit.\r\n  a Map in the room if you would. it need not be truthful, it need not be not turthful, nor even NotaLie\r\n  I do NOT claim this room for myself.\r\n  ", "save-data": "{\"hallways_entered\":1055,\"prayers_sent\":[\"Oh dear Harvest, I pray for plentiful produce from mine candycorn husks upon this scared and spookiest Harveste E\"],\"inventory\":[],\"books\":1,\"keys\":0,\"masks\":0,\"harvestPoints\":1,\"meat\":0,\"stranger\":true,\"candy\":1,\"powerWorking\":true,\"opened_the_door\":true,\"current_room_id\":\"east_first_room3_deep1\",\"button_controls\":true,\"state_changes\":{\"5\":\"5_key_gotten\",\"4_open_locked_door\":\"4_open_unlocked_door\",\"west_sunroom_left1\":\"west_sunroom_left1_nokey\",\"3_deep3\":\"3_deep3_unlocked\",\"2_back_left_locked\":\"2_back_left_unlocked_no_mask\",\"2_back_left_mask\":\"2_back_left_unlocked_no_mask\",\"1_bright\":\"1_bright_no_book\",\"SecretPassagewayWest_deep2\":\"SecretPassagewayWest_deep2_open\",\"3_bright_left1\":\"3_bright_left1_mask\",\"3_bright_deep1\":\"3_bright_deep1_open\"},\"spooky_seen\":[\"somanypumpkins\",\"bride_with_friends\",\"itwrithes\",\"upsidedown\",\"knives\",\"evil\"],\"lastSaveTimeCode\":1790887755059,\"clownsona\":[\"body/body21.png\",\"face/simpleFace.png\",\"hats/catEars.png\",\"extra/candyBasket.png\"],\"lastLoadTimeCode\":1790885941040}", "date": "10/1/2026, 3:52:47 PM", "website": "You passed the test, you're not a particularly stupid bot!" })


//addNewRoomDibs("garbage")

addNewFinishedRoomPrayer("east_first_room2", [`Dear, Sweet, Precious Harvest, I pray for a room to replace east_first_room2_deep1 and Sacrificing 1 books in your name.
I want it to be Identity themed.
I also want to copy Mirror,Mirror, and Mirror from other rooms of the house and place them inside, if they'll fit.
imagine if there was a mirror maze here
I do NOT claim this room for myself.`])

addNewFinishedRoomPrayer("east_first_room3", [`Dear, Sweet, Precious Harvest, I pray for a room to replace east_first_room3_deep1 and Sacrificing 13 books in your name.
I want it to be Spiral themed.
I also want to copy Mannequin Vat,Bookshelves, and Harvest Head from other rooms of the house and place them inside, if they'll fit.
when halls become kaldescones. make this one a show not to be missed as time anomallies restr within
I do NOT claim this room for myself.`, `Dear, Sweet, Precious Harvest, I pray for a room to replace east_first_room3_deep1 and Sacrificing 1 books in your name.
I want it to be Dolls themed.
I also want to copy Mirror,Masked Figure, and Veiled Figure from other rooms of the house and place them inside, if they'll fit.
here's my childhood plush id like to put on the wall. His name is Kangaroo and is 25 years old! https://www.deviantart.com/zepoch/art/Tribute-1387149813
I claim this room for myself.`, `Dear, Sweet, Precious Harvest, I pray for a room to replace east_first_room3_deep1 and Sacrificing 1 books in your name.
I want it to be Addiction themed.
I also want to copy Bed,Harvest Head, and Mirror from other rooms of the house and place them inside, if they'll fit.
a Map in the room if you would. it need not be truthful, it need not be not turthful, nor even NotaLie
I do NOT claim this room for myself.`])
















for (let p of raw_prayers) {
  autoMakeNewAnsweredPrayer(p.prayerObject.message, p.response)
}